### ISSUE TITLE
The path of the annotation file

### ISSUE THREAD

**Issue by chenjoya** [facebookresearch/ego4d-goalstep#3]
Hi Yale! Thanks for your amazing work! We have been waiting for its release to do some evaluation. So excited! 

I just follow your provided command to download the annotation, but I cannot find it:

![image](https://github.com/facebookresearch/ego4d-goalstep/assets/20626415/e4beb376-7c9e-4e45-b3d5-ef3748c5c074)

Is the annotation merged with other benchmarks?

**Comment by yalesong** [comment]
Hi Joya! Thanks for the early interest! I am looping in @miguelmartin75 for help on download. The goal-step annotation is independent of other benchmarks at the moment.

**Comment by miguelmartin75** [comment]
Can you upgrade your ego4d package, i.e pip install ego4d --upgrade

Then redownload. Let me know if that still doesn't work.

**Comment by yalesong** [comment]
Hope this resolved the issue, Joya. Closing for now but feel free to bring this back if the issue persists.

**Comment by chenjoya** [comment]
Yes done! Thank you so much! Happy new year!

**Comment by rmnthn** [comment]
Hi @miguelmartin75, when I tried to download the annotations using "ego4d --datasets annotations --benchmark goalstep -o ./goalstep_data", I get the "botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden" error. Anything I am missing?
(Upgraded the ego4d pip package as well but it doesn't help.)

**Comment by miguelmartin75** [comment]
@rmnthn 

Please ensure you have your `aws` client configured with your license keys prior to downloading. In other words, `pip install awscli` and `aws configure` => insert your keys.
