### ISSUE TITLE
goalstep_video_groups.tsv not found

### ISSUE THREAD

**Issue by ayiyayi** [facebookresearch/ego4d-goalstep#4]
Hi Yale! 
Thanks for your excellent work and code shareing!  I met some error when using `python -m tools.aggregate_features`,  could you please tell me how to get `goalstep_video_groups.tsv`? I have tried `ego4d --datasets annotations --benchmark goalstep`, but didn't find it.
Thank you very much. ^_^

**Comment by yalesong** [comment]
Thanks for flagging this. We are planning an update to the CLI repo to support an upcoming Ego4D challenge. The missing file is our under radar and will be resolved with the next update! Let me leave this issue open for now, we'll close this once after we update our repo.

**Comment by yalesong** [comment]
The repository is now updated with the missing file.
