### ISSUE TITLE
Missing  query and annotation_uid in test annotation file

### ISSUE THREAD

**Issue by ayiyayi** [facebookresearch/ego4d-goalstep#5]
Hi Yale!
Following Step Grounding Challenge submission guidelines,  submission file should include `annotation_uid` and `query_idx` information. But in the official test_unannotated.json, only `video_uid` is provided. How could I get additional information?

Best,
Ayiyayi

**Comment by yalesong** [comment]
We've updated the repository with the test split file containing the missing information.
