### ISSUE TITLE
Still miss annotation_uid in test annotation file

### ISSUE THREAD

**Issue by ayiyayi** [facebookresearch/ego4d-goalstep#7]
Hi Yale!
Thank you so much for generously sharing the data. I have 2 questions regarding the test file in the repository. 
1. it doesn't include the `annotation_uid`, which is required for submission to ego4d step-grounding challenge. How could I get this information?
2. what does `segment_count` mean in test file?

Thank you once again for your kindness help.

Best,
Ayiyayi

**Comment by Tushar-N** [comment]
Hi, thanks for your interest in the challenge.
1. This will be added into the json files automatically when the raw annotation files [are parsed](https://github.com/facebookresearch/ego4d-goalstep/blob/b4fe5768f1595b80a3367186f4c5316b979d04fb/step_grounding/tools/parse_goalstep_jsons.py#L26). 
2. Segment count refers to the number of times the same keystep description occurs in the test video. i.e., if the camera-wearer "cuts onions" 4 times during the course of the recipe then `segment_count = 4`. The evaluation metric will account for this as well (a prediction is correct if it matches with any gt window).

**Comment by ayiyayi** [comment]
Thank you so much!
