### ISSUE TITLE
Meaning of videos ids start with "grp"

### ISSUE THREAD

**Issue by hyf015** [facebookresearch/ego4d-goalstep#9]
Hi, thank you very much for the release of this dataset!
Just a quick question, I wonder what the video IDs that start with "grp-" mean in the annotation files?

**Comment by yalesong** [comment]
Hi Yifei!

When annotating goal-step, we realized some of the videos from Ego4D could be concatenated back-to-back to provide longer storyline. This was important for goal-step annotation as having long temporal context is beneficial for identifying goals and steps. Hope this clarifies!
